version: '3.8'

services:
  prod:
    #image: kamoskovs/nodejs2022q2-service_prod
    env_file:
      - .env
    container_name: nodejs2022Q2-service
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    networks:
      - nesjs-network
    restart: unless-stopped
    environment:
      TYPEORM_HOST: postgres

  postgres:
    #image: kamoskovs/nodejs2022q2-service_postgres
    env_file:
      - .env
    container_name: mypostgres
    build:
      context: .
      dockerfile: ./DockerfilePg
    networks:
      - nesjs-network
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  nesjs-network:
volumes:
  pgdata: